### ISSUE TITLE
unicode +- sign

### ISSUE THREAD

**Issue by bytelinker** [jagerber48/sciform#1]
Hello,

thank you very much for this package! Is there any option to format the +/- as unicode ± (https://en.wikipedia.org/wiki/Plus%E2%80%93minus_sign), please? Or where do I find the documentation for this option, if already realized, please?

sform2 = sciform.Formatter(precision=2, format_mode=sciform.FormatMode.ENGINEERING, use_prefix=True)

v2 = 1.234567890E-12
u2 = 0.01234E-12

print(sform2(v2, u2))

(1.235 +/- 0.012) p

(1.235 ± 0.012) p

All the best 
bytelinker

**Comment by jagerber48** [comment]
Hello @bytelinker, thank you for your suggestion. There is not yet an option to encode the +/- symbols as ±, but this is on the short list of features that I plan to add soon (hopefully within 2 weeks at the most). A question for you. I've been planning to have this feature be realized under a "pretty printing" option. this is similar to how the [uncertainties package](url) realizes this functionality now. Using the pretty print option We would have (2.00 +/- 0.10)e-01 formatted as (2.00±0.10)×10<sup>-1</sup>. This is, 

- The +/- would be replaced by ±
- The e-01 symbol would be replaced by  ×10<sup>-1</sup>

In the interested of handling the already large list of options, would it be satisfactory to you to have both of these changes available in one "pretty print" option, or would you prefer a dedicated option for replacing +/- by ±. I see that you're using the prefix mode, so ×10<sup>-1</sup> would be irrelevant to the case you've shown.

**Comment by bytelinker** [comment]
Hello @jagerber48 
I found this package due to the f-String discussion https://discuss.python.org/t/new-format-specifiers-for-string-formatting-of-floats-with-si-and-iec-prefixes/26914/44. I needed a solution for prefix, which I found with this package.

1. Using Unicode pm should be a general option. So everybody can decide on his own needs.
2. Changing e-01  to ×10-1 (-1 should be in the exponent) can be a good solution. But when using bad typesetting and too small character sizes in further processing in other software it can be difficult to read the numbers in the exponent. So it should be an uncoupled option, too.
3. An additional option could be rounding of value in unit and uncertainty in % or ppm of value  using the correct numbers of significant figures for both. This could be realized by input of value in unit and uncertainty in unit  and option -uncertainty_output_unit=percent|ppm.

Many aspects of number formatting are also solved in https://ctan.org/pkg/siunitx?lang=de.

all the best 
bytelinker

**Comment by jagerber48** [comment]
@bytelinker 

Ok, I will keep unicode pm and superscript exponents as separate options.

In the latest stable version there is an untested percent option, but I'm currently modifying its behavior and getting it tested. It will work for value/uncertainty formatting. 

The ppm type format is interesting. I will consider adding it. One question is how to handle the `1e-3` order of magnitude. I've personally been using ppth here for parts per thousand, but that is not standard notation.

Yes, I've used and had a look at siunitx and been in contact with the author on one issue. I think there's a lot more I could learn from studying that package.

**Comment by jagerber48** [comment]
@bytelinker version 0.14.0 contains a `unicode_pm` option.

**Comment by jagerber48** [comment]
@bytelinker version 0.17.0 includes "parts-per" notation. Version 0.17.0 also changes the `use_prefix` option to `prefix_exp`.

**Comment by bytelinker** [comment]
@jagerber48 
There are some sources of information:
International:
https://www.bipm.org/en/publications/si-brochure
National:
https://www.nist.gov/publications/international-system-units-si-2019-edition
which is also referencing
https://www.nist.gov/publications/international-system-units-si-2008-edition

Hope this helps
bytelinker

**Comment by bytelinker** [comment]
@jagerber48 
Perhaps I was to short on my description of a possible combined unit and percentage mode:
sform = sciform.Formatter(precision=2, unicode_pm=True)
#input
a_value = 1.23456789
a_unc = 0.056789
#sform = sciform.Formatter(precision=2, unicode_pm=True, output_unc='percent'|'ppm', unit_str='unit)
a_unc_rel_percent = 100 * a_unc/a_value
#round a_value by precision and a_unc, calculate a_unc_rel_percent|ppm, round result by precision
print(f'unc_rel = {a_unc_rel_percent:.1f} %')
print(f'({sform(a_value, a_unc)}) unit')
print(f'{a_value:.3f} unit ± {4.6} %')
#output:
'''
unc_rel = 4.6 %
(1.235 ± 0.057) unit
1.235 unit ± 4.6 %
'''
